version: "3"

services:
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   ports:
  #     - 6000:5000
  #   depends_on:
  #     - app
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_myadmin_backend
    ports:
      - "8200:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ROOT_PASSWORD=root
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=fesp_backend
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    ports:
      - "3306"
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: backend
    container_name: Web_backend
    restart: always
    environment:
      - DB_SERVER=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=fesp_backend
      - BASE_URL=/fesp_backend
      - SECRET＝testsecret
    volumes:
      - ./src:/app/src
    ports:
      - 5000:5000
    depends_on:
      - mysql
    expose:
      - 5000
